show_parent = true
view_reversed = false
header_footer_swapped = false
list_cycle = true

[colors]
header_bg = "Reset"
header_fg = "White"
footer_normal_bg = "Reset"
footer_normal_fg = "White"
footer_search_bg = "Reset"
footer_search_fg = "Yellow"
focus_border = "LightBlue"
normal_border = "DarkGray"
highlight_bg = "DarkGray"
highlight_fg = "LightBlue"
match_fg = "Red"
dir_fg = "LightBlue"
file_fg = "White"
exe_fg = "Green"
symlink_fg = "Magenta"

[titles]
parent = ""
current = ""
preview = ""
grep = ""

[symbols]
highlight = "❱ "
normal = "   "
dir_suffix = "/"

[strings]
path_prefix = "  "
no_item = " No item selected "
grep_empty = " No matches found "
grep_prompt = ""

[borders.parent]
position = "none"
kind = ""

[borders.current]
position = "vertical"
kind = ""

[borders.preview]
position = "none"
kind = ""

[icons]
dir = ""
file = ""
exe = ""
symlink = ""

[icons.extensions]
h = ""
matlab = ""
vba = ""
d = ""
scss = ""
env = ""
deb = ""
ini = ""
crystal = ""
flac = "󰎆"
dart = ""
conf = ""
exe = ""
img = ""
elm = ""
svelte = ""
avi = "󰕧"
so = ""
res = ""
org = ""
jpeg = "󰋩"
ico = "󰋩"
sqlite = ""
cmake = ""
f90 = "󰈤"
cargo = ""
rpm = ""
agda = ""
zig = "⚡"
go = ""
haxe = ""
mp4 = "󰕧"
kt = ""
clj = ""
rkt = ""
graphql = ""
nim = ""
bash = ""
vy = ""
csv = ""
m = ""
hbs = ""
fsx = ""
html = ""
nix = ""
dockerfile = ""
md = ""
xlsx = "󰈛"
rb = ""
svg = "󰋩"
webm = "󰕧"
ogg = "󰎆"
iso = ""
woff2 = ""
mli = ""
pl = ""
bat = ""
gz = ""
move = ""
markdown = ""
jinja = ""
mov = "󰕧"
package = ""
ex = ""
dylib = ""
el = ""
vala = ""
pug = ""
hpp = ""
tcl = ""
hxml = ""
pony = ""
doc = "󰈬"
pptx = "󰈧"
png = "󰋩"
cbl = ""
sed = ""
zst = ""
aac = "󰎆"
twig = ""
fish = ""
slim = ""
sass = ""
jpg = "󰋩"
lua = ""
cpp = ""
ts = "󰛦"
css = ""
log = ""
mkv = "󰕧"
liquid = ""
cob = ""
bmp = "󰋩"
zip = ""
sh = ""
exs = ""
mm = ""
tex = ""
coffee = ""
c = ""
scm = ""
docx = "󰈬"
less = ""
fs = ""
cfg = ""
otf = ""
tsx = ""
erl = ""
thrift = ""
pm = ""
v = ""
mp3 = "󰎆"
ejs = ""
reason = ""
rs = ""
lisp = ""
pas = ""
lock = ""
json = ""
htm = ""
gitattributes = ""
ml = ""
haml = ""
coq = ""
gif = "󰋩"
ps1 = ""
proto = ""
litcoffee = ""
groovy = ""
purs = ""
mustache = ""
txt = "󰈙"
genie = ""
rst = ""
prisma = ""
js = ""
py = ""
pascal = ""
toml = ""
solidity = ""
fsharp = ""
jinja2 = ""
tla = "󰨇"
xz = ""
octave = ""
7z = ""
scala = ""
m4a = "󰕧"
rar = ""
bz2 = ""
java = ""
fortran = "󰈤"
dll = ""
makefile = ""
gradle = ""
jsx = ""
cmd = ""
kts = ""
dockerignore = ""
gql = ""
webp = "󰋩"
wav = "󰎆"
awk = ""
jl = ""
yml = ""
lhs = ""
thy = ""
gitignore = ""
r = "ﳒ"
odin = ""
pdf = "󰈯"
ppt = "󰈧"
tar = ""
woff = ""
db = ""
cljs = ""
yaml = ""
idr = ""
php = ""
xml = "󰗀"
styl = ""
tera = ""
editorconfig = ""
astro = ""
swift = ""
sql = ""
hs = ""
jade = ""
prolog = ""
lean = ""
f = "󰈤"
xls = "󰈛"
tgz = ""
vue = ""
zsh = ""
jsonc = ""
ttf = ""
eot = ""
isabelle = ""
apk = ""
blade = ""

[icons.named]
gitignore = ""
prettierrc = ""
"tslint.json" = ""
"CMakeLists.txt" = ""
"Cargo.toml" = ""
"docker-compose.yaml" = ""
gitattributes = ""
editorconfig = ""
"Pipfile.lock" = ""
Makefile = ""
LICENSE = ""
"requirements.txt" = ""
"Gemfile.lock" = ""
"postcss.config.js" = ""
"babel.config.json" = ""
README = ""
".config" = ""
Vagrantfile = ""
"webpack.config.js" = ""
stylelintrc = ""
COPYING = ""
eslintrc = ""
"stylelint.json" = ""
CHANGELOG = ""
"prettier.json" = ""
"tsconfig.json" = ""
"rollup.config.js" = ""
Pipfile = ""
"docker-compose.yml" = ""
Dockerfile = ""
"package.json" = ""
Gemfile = ""
dockerignore = ""
TODO = ""
CONTRIBUTING = ""
"eslint.json" = ""
"vite.config.js" = ""
CODE_OF_CONDUCT = ""
"README.md" = ""
"jest.config.js" = ""
