eval "$(oh-my-posh init bash --config "$XDG_CONFIG_HOME"/oh-my-posh/spaceship.omp.json)"
eval "$(fnm env --use-on-cd --shell bash)"
eval "$(uv generate-shell-completion bash)"
eval "$(uvx --generate-shell-completion bash)"
# eval "$(rsp --init)"
eval "$(zoxide init bash)"
# eval "$(tv init bash)"
# eval "$(starship init bash)"
