export PATH="$HOME/.config/bashrc/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.nimble/bin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$PNPM_HOME:$PATH"
export PATH="$FNM_PATH:$PATH"
export PATH="$BUN_INSTALL/bin:$PATH"
