ignored = [
    ".config/tdx",
    ".config/lyse",
    ".local/share/glazepkg",
    ".local/share/fnm",
    ".local/bin/mdterm",
    ".local/bin/drift",
    ".local/bin/numpy-config",
    ".config/Code/WebStorage",
    ".config/redditsub/monitor.log",
    "target",
    ".config/Code/logs",
    ".config/Vayou",
    ".modelscope",
    ".local/share/waves",
    ".config/mdfried",
    ".vscode-shared",
    ".local/share/iwctl",
    ".config/bym",
    "downloads",
    ".local/share/user-places.xbel.tbcache",
    ".local/bin/ltmanage",
    ".local/share/user-places.xbel",
    ".local/share/mimeapps.list",
    ".dotnet",
    ".local/share/chrome-devtools-mcp",
    ".config/Code/DawnWebGPUCache",
    ".local/share/go-musicfox",
    ".local/share/gemini",
    ".local/share/keyrings",
    "Pictures/movie",
    ".local/bin/avdl",
    ".local/share/vswaybar-studio",
    ".local/bin/sg",
    ".local/share/zai",
    ".local/bin/tmdb",
    ".local/bin/kitten-tts",
    "logs",
    ".local/bin/gpk",
    ".cargo/.package-cache",
    ".config/Code/DIPS",
    ".config/bashrc/local.bash",
    ".local/bin/dotmgr",
    ".claude.json",
    ".local/bin/netorbit",
    ".config/opencode/node_modules",
    ".local/bin/ds-free-api",
    ".local/share/ansifont",
    ".config/termshark",
    ".local/share/gstreamer-1.0",
    ".local/share/flatpak",
    ".claude",
    ".local/bin/bluekeys",
    ".local/bin/see",
    ".pnpm",
    ".config/gtk-4.0",
    ".local/share/CMakeTools",
    ".local/share/deepseek",
    ".local/share/systemctl-tui",
    ".venv",
    ".local/bin/procinfo",
    ".config/obs-studio",
    ".config/opencode/skills",
    ".config/lyre",
    ".config/Code/languagepacks.json",
    ".local/bin/twitter-media-downloader",
    ".local/share/opencode",
    ".local/share/webkitgtk-4.1",
    ".local/share/applications/mimeapps.list",
    ".cargo/registry",
    ".local/bin/nano-ffmpeg",
    ".local/share/warp-terminal",
    ".local/share/bluetui",
    ".trash",
    "Pictures/sr",
    ".local/bin/ascii-art-generator",
    ".config/transmission",
    "Thumbs.db",
    ".config/Code/User/History",
    "Pictures/image_0005.png",
    ".local/bin/kairo",
    ".bash_history",
    ".local/share/mime",
    ".config/Code/User/profiles",
    ".config/Code/CachedData",
    ".local/share/jiq",
    "Pictures/gifs",
    ".local/share/argos-translate",
    ".local/lib",
    "Videos",
    ".config/Code/Partitions",
    ".config/Code/Network Persistent State",
    ".pki",
    ".config/procps",
    ".w3m",
    ".local/share/ztools",
    ".local/bin/mpv-tui",
    ".local/share/Meltytech",
    ".commandok",
    ".local/share/tracexec",
    ".local/share/kilo",
    ".config/Code/User/workspaceStorage",
    ".local/bin/cwalk",
    ".local/bin/snake",
    ".local/bin/bin",
    ".config/Code/User/keybindings.json",
    ".cargo/.crates.toml",
    ".config/Code/TransportSecurity",
    ".dotfiles",
    ".local/bin/reko",
    ".DS_Store",
    ".config/viu",
    ".local/share/reshell",
    ".config/opencode/package.json",
    ".local/bin/buddy",
    "Pictures/gallery-dl",
    ".local/bin/libretranslate",
    ".local/bin/zy",
    ".local/share/zarumet",
    "stats.json",
    ".config/Code/CachedProfilesData",
    ".config/Code/User/sync",
    ".local/bin/pyy",
    ".local/bin/tpix",
    ".cargo/.global-cache",
    ".config/Code/GPUCache",
    ".local/bin/peck",
    ".config/google-chrome",
    ".local/share/godot",
    ".local/share/applications/mimeinfo.cache",
    ".config/Code/Backups",
    ".rustup",
    ".config/Code/Crashpad",
    ".local/share/opentui",
    ".config/extensions",
    ".vscode",
    ".local/share/yarn",
    ".local/bin/qrcp",
    ".local/bin/aitutor",
    ".twmd",
    ".local/share/pakeplus",
    ".local/share/google-ai-mode-mcp",
    ".local/bin/tmlshock",
    ".local/bin/termbook",
    ".local/bin/f2py",
    ".cargo/.rustc_info.json",
    "Pictures/wall",
    ".local/bin/spt",
    ".local/bin/workspace-launcher",
    ".cache",
    ".go",
    ".local/share/bash-completion",
    ".local/bin/dawn",
    ".fnm",
    "Downloads",
    ".config/Code/shared_proto_db",
    ".local/bin/ascii-image-converter",
    ".config/Code/User/agent-sessions.code-workspace",
    ".local/bin/gws",
    ".local/bin/nitch",
    ".local/share/minimax",
    ".config/Code/Cookies-journal",
    ".wdm",
    ".vdl",
    ".config/redditsub/config.json",
    ".local/bin/gitcredits",
    ".config/pulse",
    ".local/state",
    ".local/bin/kitten-tts-server",
    ".config/Code/Service Worker",
    ".local/bin/xiaohongshu-mcp",
    ".cargo/git",
    ".config/Code/Cache",
    ".local/share/fcitx5",
    "Documents",
    "Pictures/image_0554.jpg",
    ".local/bin/crontab-guru",
    ".config/go",
    ".config/bili-term/cookies.txt",
    "Desktop",
    ".local/bin/termgram",
    ".config/Code/Code Cache",
    ".local/share/fish",
    ".local/bin/upiano",
    ".termbook",
    ".local/share/nwg-look",
    ".icons",
    "Pictures/image_0004.png",
    "Pictures/screenshots",
    ".config/Code/CachedConfigurations",
    ".local/share/ymp",
    ".local/bin/bit",
    ".local/bin/instaloader",
    ".local/bin/xiaohongshu-login",
    ".qwen",
    ".config/Code/Dictionaries",
    ".config/Code/code.lock",
    ".config/Code/Local Storage",
    ".config/Code/SharedStorage",
    ".config/Code/machineid",
    ".config/menus",
    ".local/share/hyprwave",
    ".local/share/icons",
    ".config/gtk-3.0",
    ".sr",
    ".local/share/gh",
    ".dawn",
    ".local/bin/modelscope",
    ".config/zen",
    ".local/share/powershell",
    ".local/bin/eget",
    ".local/bin/mihomoui",
    ".local/bin/deadbranch",
    ".local/bin/biliup",
    "Pictures/temp",
    ".local/bin/sr",
    ".config/Code/DIPS-wal",
    ".local/bin/commandok",
    ".local/share/user-places.xbel.bak",
    ".config/Code/Shared Dictionary",
    ".npm",
    ".local/bin/vsd",
    ".config/Code/Trust Tokens",
    ".local/share/TelegramDesktop",
    ".local/share/turborepo",
    ".local/share/qutebrowser",
    "Downloads/github/hyprland",
    ".kittentts",
    ".config/Code/CachedExtensionVSIXs",
    ".config/opencode/package-lock.json",
    ".android",
    "Backups",
    ".local/share/codebook",
    ".config/ibus",
    "venv",
    ".config/Code/SharedStorage-wal",
    ".local/share/crush",
    ".local/share/zoxide",
    ".local/bin/ytsurf",
    ".local/bin/alayer",
    "node_modules",
    ".gnupg",
    "Pictures/nsfw",
    ".config/Code/blob_storage",
    ".qwen3_asr",
    ".config/fcitx",
    ".local/share/yad",
    ".config/Code/VideoDecodeStats",
    ".config/xvd",
    ".config/qt6ct",
    ".cargo/bin",
    ".config/nano-ffmpeg",
    ".local/share/wayscriber",
    ".kilocode",
    "Pictures/image_0051.png",
    ".ssh",
    ".config/Code/Cookies",
    ".cargo/.package-cache-mutate",
    ".local/bin/jg",
    ".local/share/recently-used.xbel",
    ".local/share/youtui",
    "Music",
    ".local/share/mihomoui",
    ".local/share/hyprland",
    ".whisper",
    ".local/share/qwen",
    ".local/bin/dictation",
    ".local/share/Trash",
    "Projects",
    ".config/Code/.org.chromium.Chromium.fHUdrT",
    ".bun",
    ".local/share/pnpm",
    ".config/kairo",
    ".local/bin/reshell",
    ".config/opencode/bun.lock",
    ".local/share/nvim",
    ".local/bin/lsix",
    ".config/nwg-look",
    ".config/Code/User/snippets",
    ".local/bin/env-pilot",
    "__pycache__",
    ".config/Code/User/globalStorage",
    ".local/share/com.neil.synchive",
    ".local/share/television",
    ".local/share/com.vayou.desktop",
    ".viminfo",
    ".local/share/bulletty",
    ".config/Code/User/chatLanguageModels.json",
    "Pictures/telegraph",
    ".config/configstore",
    ".zen",
    ".local/bin/tdx",
    ".config/opencode/.gitignore",
    ".local/bin/baeru",
    ".qwen3_tts",
    ".local/share/uv",
    ".config/Code/Preferences",
    ".config/Code/DawnGraphiteCache",
    "Pictures/image_0565.png",
    ".deepseek",
    ".codex",
    ".local/bin/envlens",
    ".local/bin/jiq",
    "Pictures/develop",
    ".config/Code/Trust Tokens-journal",
    ".config/Code/Session Storage",
    "Pictures/x",
    ".cargo/.crates2.json",
]
