

[main]
#font=Monofur Nerd Font Mono:size=20
pad=4x4
selection-target=both
include=/home/neil/.cache/cwal/colors-foot.ini
initial-color-theme=dark
font=JetBrainsMonoNL Nerd Font:size=18


[cursor]
style=beam
beam-thickness=3
underline-thickness=2px


[colors-dark]
blur=yes
cursor=0E0F12 ffa500
selection-background=84a8e5
selection-foreground=010101
search-box-no-match=ffffff c5692c
search-box-match=3cc97b 0e1011

[csd]
border-width=0
#preferred=none

