#!/bin/bash

CONFIG_FILE="$HOME/.config/hypr/hyprratio.conf"

apply_ratio_rules() {
    sleep 0.3

    local DATA
    DATA=$(hyprctl -j clients)
    local ACTIVE_WS
    ACTIVE_WS=$(hyprctl -j activeworkspace | jq '.id')

    mapfile -t clients < <(echo "$DATA" | jq -r ".[] | select(.workspace.id == $ACTIVE_WS and .floating == false) | .class" | tr '[:upper:]' '[:lower:]' | sort)

    if [ "${#clients[@]}" -eq 2 ]; then
        c1="${clients[0]}"
        c2="${clients[1]}"

        [ ! -f "$CONFIG_FILE" ] && return

        while read -r conf_c1 conf_c2 ratio; do
            [[ "$conf_c1" =~ ^#.*$ || -z "$conf_c1" ]] && continue

            read -r sc1 sc2 < <(echo "$conf_c1 $conf_c2" | tr ' ' '\n' | tr '[:upper:]' '[:lower:]' | sort | xargs)

            if [[ "$c1" == "$sc1" && "$c2" == "$sc2" ]]; then
                local offset=$(echo "$ratio - 0.5" | bc)
                hyprctl dispatch splitratio exact "$ratio" >/dev/null 2>&1 ||
                    (hyprctl dispatch splitratio 0 && hyprctl dispatch splitratio "$offset")
                return
            fi
        done <"$CONFIG_FILE"
    fi
}

check_deps() {
    local missing=()
    for cmd in socat jq bc; do
        command -v "$cmd" &>/dev/null || missing+=("$cmd")
    done
    if [ ${#missing[@]} -ne 0 ]; then
        notify-send "Hyprland Script Error" "Please install: ${missing[*]}"
        exit 1
    fi
}

check_deps

socat -U - UNIX-CONNECT:"$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do
    case $line in
    openwindow* | closewindow* | movewindow*)
        apply_ratio_rules
        ;;
    workspace*)
        sleep 0.5
        apply_ratio_rules
        ;;
    esac
done
