#!/usr/bin/env bash

current=$(hyprctl getoption general:layout -j | jq -r '.str')

if [ "$current" == "dwindle" ]; then
    hyprctl keyword general:layout "scrolling"
    notify-send "Layout" "Switched to Scrolling" -i input-mouse
else
    hyprctl keyword general:layout "dwindle"
    notify-send "Layout" "Switched to Dwindle" -i input-mouse
fi
