#!/bin/bash

cdialog() {
  yad --title='Confirm ?' --width=250 --height=100 --borders=10 --fixed --undecorated --center --buttons-layout=center --button=Yes:0 --button=No:1 --text="Are you sure?" --text-align=center
}

if [[ "$1" == '--shutdown' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    systemctl poweroff
  else
    exit
  fi
elif [[ "$1" == '--reboot' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    systemctl reboot
  else
    exit
  fi
elif [[ "$1" == '--hibernate' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    systemctl hibernate
  else
    exit
  fi
elif [[ "$1" == '--lock' ]]; then
  ~/.config/hypr/scripts/lockscreen
elif [[ "$1" == '--suspend' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    # mpc -q pause
    pamixer -m
    ~/.config/hypr/scripts/lockscreen
    systemctl suspend
  else
    exit
  fi
elif [[ "$1" == '--logout' ]]; then
  cdialog
  if [[ "$?" == 0 ]]; then
    kill -9 -1
  else
    exit
  fi
fi
