[main]
font=JetBrainsMonoNL Nerd Font:size=16
pad=0x0
selection-target=both

[cursor]
style=beam
beam-thickness=3
underline-thickness=2px


[colors-dark]
# leicht transparente Bar-Optik
alpha=1
cursor=0E0F12 ffa500
# Hintergrund: tiefes, neutrales Blau/Grau
background=0e1011
foreground=b4befe

# Auswahl: heller, aber nicht weiß
selection-background=84a8e5
selection-foreground=010101
search-box-no-match=ffffff c5692c
search-box-match=3cc97b 0e1011

# -------------------------------------------
# REGULAR (dunkle, gedämpfte Farbtöne)
# -------------------------------------------
regular0=0E1011    # black     (background)
regular1=9b565a    # red       (desaturated)
regular2=19DF86    # green
regular3=D29500    # yellow    (gold-beige)
regular4=88B3FA    # blue
regular5=8d6f99    # magenta
regular6=5d9ba2    # cyan
regular7=d7e2eb    # white     (foreground)

# -------------------------------------------
# BRIGHT (nur leicht heller, nicht knallig)
# -------------------------------------------
bright0=141b22     # bright black (soft)
bright1=ba6a6f     # bright red
bright2=89a783     # bright green
bright3=c8b97b     # bright yellow
bright4=6f95be     # bright blue
bright5=a785b3     # bright magenta
bright6=73b7c2     # bright cyan
bright7=f4f7fa     # bright white

[csd]
border-width=0
preferred=none

